import path from 'node:path';
import { fileURLToPath } from 'node:url';
import dotenv from 'dotenv';
import { PrismaClient } from '@prisma/client';

dotenv.config({
  path: path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../.env'),
});

const prisma = new PrismaClient();

const companies = [
  {
    id: 'c01',
    name: 'Codegod Table',
    type: 'Restaurant',
    area: 'Bandra',
    address: 'Pali Hill, Bandra West',
    lat: 19.0627,
    lng: 72.8296,
    rating: 4.6,
    reviewCount: 18,
    responseRate: 0.94,
    avgResponseMins: 12,
    fulfillmentRate: 0.97,
    verified: true,
    joinedAt: new Date('2026-01-14'),
    clerkUserId: 'user_3JrEUGGgkBghvEhPRvQkex6JocW',
    ownerEmail: 'cooodegod@gmail.com',
  },
  {
    id: 'c02',
    name: 'Harbour Hall Co.',
    type: 'Banquet Hall',
    area: 'Lower Parel',
    address: 'Tulsi Pipe Road, Lower Parel',
    lat: 18.9976,
    lng: 72.8246,
    rating: 4.5,
    reviewCount: 41,
    responseRate: 0.9,
    avgResponseMins: 18,
    fulfillmentRate: 0.95,
    verified: true,
    joinedAt: new Date('2025-11-02'),
    clerkUserId: 'user_3JrFqZwjWCqb6sErJHqiP5XfnGd',
    ownerEmail: 'surajy.tech@gmail.com',
  },
  {
    id: 'c03',
    name: 'Cold Cart Kitchens',
    type: 'Caterer',
    area: 'Andheri',
    address: 'Veera Desai Road, Andheri West',
    lat: 19.1362,
    lng: 72.8331,
    rating: 4.4,
    reviewCount: 27,
    responseRate: 0.88,
    avgResponseMins: 22,
    fulfillmentRate: 0.93,
    verified: true,
    joinedAt: new Date('2025-08-19'),
    clerkUserId: 'user_3Js14IphTxmvLsxebTb9o61Bb2c',
    ownerEmail: 'coldcart+clerk_test@example.com',
  },
  {
    id: 'c04',
    name: 'West Wharf AV',
    type: 'Events',
    area: 'Juhu',
    address: 'Juhu Tara Road, Juhu',
    lat: 19.098,
    lng: 72.8265,
    rating: 4.7,
    reviewCount: 33,
    responseRate: 0.96,
    avgResponseMins: 9,
    fulfillmentRate: 0.98,
    verified: true,
    joinedAt: new Date('2025-06-30'),
    clerkUserId: 'user_3Js14rqthigx1GQrveXh5tDRpXo',
    ownerEmail: 'westwharf+clerk_test@example.com',
  },
];

const listings = [
  {
    id: 'c01a',
    businessId: 'c01',
    title: 'Private Dining Room',
    category: 'BANQUET_SPACE',
    description: 'A 28-cover dining room with its own service station, available when the restaurant floor is closed.',
    price: 8000,
    unit: 'HOUR',
    quantity: 1,
    available: 0,
    unitLabel: 'room',
    minRentalHours: 3,
    capacity: 28,
    tags: ['private', 'tasting'],
    delivers: false,
  },
  {
    id: 'c01b',
    businessId: 'c01',
    title: 'Pastry Bench — Morning',
    category: 'KITCHEN',
    description: 'Marble bench, deck oven and planetary mixer, free before the lunch service starts.',
    price: 1500,
    unit: 'HOUR',
    quantity: 1,
    available: 1,
    unitLabel: 'bench',
    minRentalHours: 3,
    tags: ['bakery', 'morning'],
    delivers: false,
  },
  {
    id: 'c02a',
    businessId: 'c02',
    title: 'Harbour Hall',
    category: 'BANQUET_SPACE',
    description: 'Pillarless hall with a pre-function foyer, in-house green room and loading bay on Tulsi Pipe Road.',
    price: 14000,
    unit: 'HOUR',
    quantity: 1,
    available: 1,
    unitLabel: 'hall',
    minRentalHours: 4,
    capacity: 180,
    tags: ['pillarless', 'AC'],
    delivers: false,
  },
  {
    id: 'c02b',
    businessId: 'c02',
    title: 'Gold Chiavari Chairs',
    category: 'CHAIRS_TABLES',
    description: 'Gold chiavari chairs with ivory cushions. Delivered, set, and collected.',
    price: 90,
    unit: 'UNIT',
    quantity: 200,
    available: 160,
    unitLabel: 'chairs',
    minRentalHours: 6,
    tags: ['wedding', 'cushioned'],
    delivers: true,
    deliveryBase: 800,
    deliveryPerKm: 40,
  },
  {
    id: 'c03a',
    businessId: 'c03',
    title: 'Night Kitchen Line',
    category: 'KITCHEN',
    description: 'Hot line with tilting pans and a blast chiller, staffed 10pm to 6am.',
    price: 3200,
    unit: 'HOUR',
    quantity: 1,
    available: 1,
    unitLabel: 'line',
    minRentalHours: 4,
    capacity: 400,
    tags: ['night', 'blast-chiller'],
    delivers: false,
  },
  {
    id: 'c03b',
    businessId: 'c03',
    title: 'Reefer Van 1.5T',
    category: 'VEHICLES',
    description: 'Temperature-controlled van, 2–8°C, with driver.',
    price: 1400,
    unit: 'HOUR',
    quantity: 2,
    available: 1,
    unitLabel: 'vans',
    minRentalHours: 4,
    tags: ['cold-chain', 'driver'],
    delivers: true,
    deliveryBase: 0,
    deliveryPerKm: 0,
  },
  {
    id: 'c04a',
    businessId: 'c04',
    title: 'Laser Projector Kit',
    category: 'AV_EQUIPMENT',
    description: '7000-lumen laser projector, 10ft fast-fold screen, and a technician for the day.',
    price: 7000,
    unit: 'DAY',
    quantity: 2,
    available: 1,
    unitLabel: 'kits',
    minRentalHours: 6,
    tags: ['projector', 'technician'],
    delivers: true,
    deliveryBase: 500,
    deliveryPerKm: 35,
  },
  {
    id: 'c04b',
    businessId: 'c04',
    title: 'Wash Lighting Kit',
    category: 'AV_EQUIPMENT',
    description: 'Moving heads, LED pars, DMX console and a small truss.',
    price: 11000,
    unit: 'DAY',
    quantity: 1,
    available: 1,
    unitLabel: 'kit',
    minRentalHours: 8,
    tags: ['lighting', 'truss'],
    delivers: true,
    deliveryBase: 700,
    deliveryPerKm: 40,
  },
];

const bookings = [
  {
    id: 'cx01',
    ref: 'SPR-C101',
    seekerId: 'c01',
    title: 'Saturday supper — extra chairs',
    status: 'PENDING',
    startAt: '2026-09-27T18:00:00+05:30',
    endAt: '2026-09-27T23:00:00+05:30',
    total: 40 * 90,
    createdAt: '2026-09-25T14:10:00+05:30',
    note: '40 gold chairs for a seated supper. We will return them the same night.',
    items: [{ resourceId: 'c02b', providerId: 'c02', quantity: 40, agreedPrice: 90 }],
    offers: [
      {
        id: 'o-cx01-1',
        resourceId: 'c02b',
        fromBusinessId: 'c01',
        toBusinessId: 'c02',
        round: 1,
        price: 90,
        quantity: 40,
        message: 'Can you deliver 40 gold chiavaris to Pali Hill by 5pm on Saturday?',
        status: 'OPEN',
      },
    ],
  },
  {
    id: 'cx02',
    ref: 'SPR-C102',
    seekerId: 'c01',
    title: 'Brunch prep — night kitchen',
    status: 'COUNTERED',
    startAt: '2026-09-28T22:00:00+05:30',
    endAt: '2026-09-29T04:00:00+05:30',
    total: 6 * 3600,
    createdAt: '2026-09-24T11:20:00+05:30',
    note: 'Need the hot line for a Monday brunch prep.',
    items: [{ resourceId: 'c03a', providerId: 'c03', quantity: 6, agreedPrice: 3600 }],
    offers: [
      {
        id: 'o-cx02-1',
        resourceId: 'c03a',
        fromBusinessId: 'c01',
        toBusinessId: 'c03',
        round: 1,
        price: 3200,
        quantity: 6,
        message: 'Six hours on the night line, 10pm to 4am. We bring our own brigade.',
        status: 'COUNTERED',
      },
      {
        id: 'o-cx02-2',
        resourceId: 'c03a',
        fromBusinessId: 'c03',
        toBusinessId: 'c01',
        round: 2,
        price: 3600,
        quantity: 6,
        message: 'Sunday night is already half committed. We can do it at ₹3,600 an hour.',
        status: 'OPEN',
      },
    ],
  },
  {
    id: 'cx03',
    ref: 'SPR-C103',
    seekerId: 'c01',
    title: 'Investor dinner projection',
    status: 'CONFIRMED',
    startAt: '2026-10-03T18:00:00+05:30',
    endAt: '2026-10-03T23:00:00+05:30',
    total: 7000,
    createdAt: '2026-09-21T16:05:00+05:30',
    note: 'One projector kit for a seated investor dinner.',
    items: [{ resourceId: 'c04a', providerId: 'c04', quantity: 1, agreedPrice: 7000 }],
    offers: [
      {
        id: 'o-cx03-1',
        resourceId: 'c04a',
        fromBusinessId: 'c01',
        toBusinessId: 'c04',
        round: 1,
        price: 7000,
        quantity: 1,
        message: 'Need the laser projector and a technician from 6pm.',
        status: 'ACCEPTED',
      },
    ],
  },
  {
    id: 'cx04',
    ref: 'SPR-C104',
    seekerId: 'c01',
    title: 'Dessert run — reefer van',
    status: 'COMPLETED',
    startAt: '2026-09-21T10:00:00+05:30',
    endAt: '2026-09-21T14:00:00+05:30',
    total: 4 * 1400,
    createdAt: '2026-09-22T09:40:00+05:30',
    note: 'Four-hour cold run for plated desserts.',
    items: [{ resourceId: 'c03b', providerId: 'c03', quantity: 4, agreedPrice: 1400 }],
    offers: [
      {
        id: 'o-cx04-1',
        resourceId: 'c03b',
        fromBusinessId: 'c01',
        toBusinessId: 'c03',
        round: 1,
        price: 1400,
        quantity: 4,
        message: 'Bandra to Juhu and back, holding at 4°C.',
        status: 'ACCEPTED',
      },
    ],
    review: {
      byBusinessId: 'c01',
      rating: 5,
      text: 'Van arrived cold and the driver waited through service.',
      tags: ['on-time', 'cold-chain'],
    },
  },
  {
    id: 'cx05',
    ref: 'SPR-C105',
    seekerId: 'c02',
    title: 'Wedding cake bench',
    status: 'PENDING',
    startAt: '2026-09-29T06:00:00+05:30',
    endAt: '2026-09-29T11:00:00+05:30',
    total: 5 * 1500,
    createdAt: '2026-09-25T18:15:00+05:30',
    note: 'Morning pastry bench for a wedding cake finish.',
    items: [{ resourceId: 'c01b', providerId: 'c01', quantity: 5, agreedPrice: 1500 }],
    offers: [
      {
        id: 'o-cx05-1',
        resourceId: 'c01b',
        fromBusinessId: 'c02',
        toBusinessId: 'c01',
        round: 1,
        price: 1500,
        quantity: 5,
        message: 'Our pastry chef needs the bench 6am to 11am on Tuesday. We will be out before lunch.',
        status: 'OPEN',
      },
    ],
  },
  {
    id: 'cx06',
    ref: 'SPR-C106',
    seekerId: 'c04',
    title: 'Client tasting lunch',
    status: 'ACCEPTED',
    startAt: '2026-10-01T12:00:00+05:30',
    endAt: '2026-10-01T16:00:00+05:30',
    total: 4 * 8000,
    createdAt: '2026-09-23T13:25:00+05:30',
    note: 'Private room for a client tasting.',
    items: [{ resourceId: 'c01a', providerId: 'c01', quantity: 4, agreedPrice: 8000 }],
    offers: [
      {
        id: 'o-cx06-1',
        resourceId: 'c01a',
        fromBusinessId: 'c04',
        toBusinessId: 'c01',
        round: 1,
        price: 8000,
        quantity: 4,
        message: 'Twelve guests, noon to 4pm. We only need the room and a floor manager.',
        status: 'ACCEPTED',
      },
    ],
  },
  {
    id: 'cx07',
    ref: 'SPR-C107',
    seekerId: 'c03',
    title: 'Staff offsite lunch',
    status: 'COUNTERED',
    startAt: '2026-10-05T12:30:00+05:30',
    endAt: '2026-10-05T15:30:00+05:30',
    total: 3 * 8000,
    createdAt: '2026-09-22T17:45:00+05:30',
    note: 'Kitchen team lunch in the private room.',
    items: [{ resourceId: 'c01a', providerId: 'c01', quantity: 3, agreedPrice: 8000 }],
    offers: [
      {
        id: 'o-cx07-1',
        resourceId: 'c01a',
        fromBusinessId: 'c03',
        toBusinessId: 'c01',
        round: 1,
        price: 7000,
        quantity: 3,
        message: 'Twenty staff, three hours. Can you do ₹7,000 an hour on a Monday?',
        status: 'COUNTERED',
      },
      {
        id: 'o-cx07-2',
        resourceId: 'c01a',
        fromBusinessId: 'c01',
        toBusinessId: 'c03',
        round: 2,
        price: 8000,
        quantity: 3,
        message: 'Monday lunch is full rate. ₹8,000 an hour, and we will set a family table.',
        status: 'OPEN',
      },
    ],
  },
  {
    id: 'cx08',
    ref: 'SPR-C108',
    seekerId: 'c01',
    title: 'August lighting hire',
    status: 'COMPLETED',
    startAt: '2026-08-20T17:00:00+05:30',
    endAt: '2026-08-20T23:00:00+05:30',
    total: 11000,
    createdAt: '2026-08-18T12:00:00+05:30',
    note: 'Wash kit for a private dinner.',
    items: [{ resourceId: 'c04b', providerId: 'c04', quantity: 1, agreedPrice: 11000 }],
    offers: [
      {
        id: 'o-cx08-1',
        resourceId: 'c04b',
        fromBusinessId: 'c01',
        toBusinessId: 'c04',
        round: 1,
        price: 11000,
        quantity: 1,
        message: 'One lighting kit for the 20th.',
        status: 'ACCEPTED',
      },
    ],
  },
  {
    id: 'cx09',
    ref: 'SPR-C109',
    seekerId: 'c02',
    title: 'August tasting room',
    status: 'COMPLETED',
    startAt: '2026-08-12T12:00:00+05:30',
    endAt: '2026-08-12T15:00:00+05:30',
    total: 3 * 8000,
    createdAt: '2026-08-10T15:30:00+05:30',
    note: 'Three-hour tasting in the private room.',
    items: [{ resourceId: 'c01a', providerId: 'c01', quantity: 3, agreedPrice: 8000 }],
    offers: [
      {
        id: 'o-cx09-1',
        resourceId: 'c01a',
        fromBusinessId: 'c02',
        toBusinessId: 'c01',
        round: 1,
        price: 8000,
        quantity: 3,
        message: 'Booked and paid.',
        status: 'ACCEPTED',
      },
    ],
  },
  {
    id: 'cx10',
    ref: 'SPR-C110',
    seekerId: 'c01',
    title: 'Harbour Hall lunch',
    status: 'CONFIRMED',
    startAt: '2026-09-12T12:00:00+05:30',
    endAt: '2026-09-12T16:00:00+05:30',
    total: 4 * 14000,
    createdAt: '2026-09-08T10:15:00+05:30',
    note: 'Four hours of the hall for a seated lunch.',
    items: [{ resourceId: 'c02a', providerId: 'c02', quantity: 4, agreedPrice: 14000 }],
    offers: [
      {
        id: 'o-cx10-1',
        resourceId: 'c02a',
        fromBusinessId: 'c01',
        toBusinessId: 'c02',
        round: 1,
        price: 14000,
        quantity: 4,
        message: 'Noon to 4pm, 90 guests.',
        status: 'ACCEPTED',
      },
    ],
  },
  {
    id: 'cx11',
    ref: 'SPR-C111',
    seekerId: 'c02',
    title: 'Hall lighting for a sangeet',
    status: 'CONFIRMED',
    startAt: '2026-10-04T18:00:00+05:30',
    endAt: '2026-10-04T23:00:00+05:30',
    total: 11000,
    createdAt: '2026-09-15T19:00:00+05:30',
    note: 'Lighting kit inside Harbour Hall. Codegod Table is not a party to this.',
    items: [{ resourceId: 'c04b', providerId: 'c04', quantity: 1, agreedPrice: 11000 }],
    offers: [
      {
        id: 'o-cx11-1',
        resourceId: 'c04b',
        fromBusinessId: 'c02',
        toBusinessId: 'c04',
        round: 1,
        price: 11000,
        quantity: 1,
        message: 'Sangeet on the 4th. Load in at 2pm.',
        status: 'ACCEPTED',
      },
    ],
  },
  {
    id: 'cx12',
    ref: 'SPR-C112',
    seekerId: 'c04',
    title: 'Crew dinner in the hall',
    status: 'PENDING',
    startAt: '2026-09-30T19:00:00+05:30',
    endAt: '2026-09-30T23:00:00+05:30',
    total: 4 * 14000,
    createdAt: '2026-09-26T09:05:00+05:30',
    note: 'West Wharf booking Harbour Hall. Codegod Table is not a party to this.',
    items: [{ resourceId: 'c02a', providerId: 'c02', quantity: 4, agreedPrice: 14000 }],
    offers: [
      {
        id: 'o-cx12-1',
        resourceId: 'c02a',
        fromBusinessId: 'c04',
        toBusinessId: 'c02',
        round: 1,
        price: 14000,
        quantity: 4,
        message: 'Crew dinner, 40 people, Wednesday night.',
        status: 'OPEN',
      },
    ],
  },
];

async function main() {
  for (const company of companies) {
    await prisma.exchangeBusiness.upsert({
      where: { id: company.id },
      create: company,
      update: company,
    });
  }

  for (const listing of listings) {
    const data = {
      businessId: listing.businessId,
      title: listing.title,
      category: listing.category,
      description: listing.description,
      price: listing.price,
      unit: listing.unit,
      quantity: listing.quantity,
      available: listing.available,
      unitLabel: listing.unitLabel,
      minRentalHours: listing.minRentalHours,
      capacity: listing.capacity ?? null,
      tags: listing.tags,
      delivers: listing.delivers,
      deliveryBase: listing.deliveryBase ?? null,
      deliveryPerKm: listing.deliveryPerKm ?? null,
    };
    await prisma.exchangeListing.upsert({
      where: { id: listing.id },
      create: { id: listing.id, ...data, conditions: [] },
      update: data,
    });
  }

  const ids = bookings.map((booking) => booking.id);
  await prisma.exchangeReview.deleteMany({ where: { bookingId: { in: ids } } });
  await prisma.exchangeOffer.deleteMany({ where: { bookingId: { in: ids } } });
  await prisma.exchangeBookingItem.deleteMany({ where: { bookingId: { in: ids } } });
  await prisma.exchangeBooking.deleteMany({ where: { id: { in: ids } } });

  for (const booking of bookings) {
    await prisma.exchangeBooking.create({
      data: {
        id: booking.id,
        ref: booking.ref,
        seekerId: booking.seekerId,
        title: booking.title,
        status: booking.status,
        startAt: new Date(booking.startAt),
        endAt: new Date(booking.endAt),
        total: booking.total,
        note: booking.note,
        createdAt: new Date(booking.createdAt),
        items: { create: booking.items },
        offers: {
          create: booking.offers.map((offer) => ({
            id: offer.id,
            resourceId: offer.resourceId,
            fromBusinessId: offer.fromBusinessId,
            toBusinessId: offer.toBusinessId,
            round: offer.round,
            price: offer.price,
            quantity: offer.quantity,
            message: offer.message,
            status: offer.status,
            createdAt: new Date(booking.createdAt),
            expiresAt: new Date(new Date(booking.createdAt).getTime() + 48 * 60 * 60 * 1000),
          })),
        },
        ...(booking.review
          ? {
              reviews: {
                create: {
                  ...booking.review,
                  createdAt: new Date(booking.endAt),
                },
              },
            }
          : {}),
      },
    });
  }

  await prisma.exchangeNotification.deleteMany({ where: { id: { in: ['n-c01-1', 'n-c01-2', 'n-c01-3', 'n-c02-1'] } } });
  await prisma.exchangeNotification.createMany({
    data: [
      {
        id: 'n-c01-1',
        businessId: 'c01',
        title: 'Cold Cart countered the night kitchen',
        body: 'Sunday night is ₹3,600 an hour. Your move on brunch prep.',
        createdAt: new Date('2026-09-24T12:05:00+05:30'),
        read: false,
      },
      {
        id: 'n-c01-2',
        businessId: 'c01',
        title: 'Harbour Hall wants the pastry bench',
        body: 'Tuesday 6am–11am for a wedding cake finish.',
        createdAt: new Date('2026-09-25T18:16:00+05:30'),
        read: false,
      },
      {
        id: 'n-c01-3',
        businessId: 'c01',
        title: 'West Wharf confirmed the tasting lunch',
        body: 'Private dining room, 1 Oct, noon to 4pm.',
        createdAt: new Date('2026-09-23T13:40:00+05:30'),
        read: true,
      },
      {
        id: 'n-c02-1',
        businessId: 'c02',
        title: 'Codegod Table asked for 40 chairs',
        body: 'Saturday supper at Pali Hill. Your move.',
        createdAt: new Date('2026-09-25T14:11:00+05:30'),
        read: false,
      },
    ],
  });

  await prisma.exchangeSavedSearch.deleteMany({ where: { id: { in: ['ss-c01-1', 'ss-c01-2', 'ss-c02-1'] } } });
  await prisma.exchangeSavedSearch.createMany({
    data: [
      {
        id: 'ss-c01-1',
        businessId: 'c01',
        name: 'Chairs near Lower Parel',
        query: 'category=CHAIRS_TABLES&area=Lower%20Parel',
        createdAt: new Date('2026-09-20T09:00:00+05:30'),
        newMatches: 1,
      },
      {
        id: 'ss-c01-2',
        businessId: 'c01',
        name: 'Reefer van this week',
        query: 'category=VEHICLES&q=reefer',
        createdAt: new Date('2026-09-18T09:00:00+05:30'),
        newMatches: 0,
      },
      {
        id: 'ss-c02-1',
        businessId: 'c02',
        name: 'Morning pastry kitchens',
        query: 'category=KITCHEN&q=pastry',
        createdAt: new Date('2026-09-21T09:00:00+05:30'),
        newMatches: 1,
      },
    ],
  });

  console.log('Seeded 4 companies and the deals between them.');
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
